# Get a user key fingerprint from gpg (used for encryption/decryption)
# gpg --show-keys <key> | awk '{ print $1 }' | head -n2 | tail -n1

# Generate a host public key (used for encryption)
# sudo nix run 'nixpkgs#ssh-to-age' -- -i /etc/ssh/ssh_host_ed25519_key -o ./keys/hosts/<host>.pub

# Add secrets
# nix run 'nixpkgs#sops' -- <path-to-secret>

# If keys defined here were to change, update the secrets with the following command:
# for secret in $(find . -type f -name 'secrets.y*ml'); do nix run 'nixpkgs#sops' -- updatekeys $secret; done
keys:
  users:
    - &nicolas FBD3C792CCBD599671A6975AEC6884FA72B9465A
  hosts:
    - &g-xps age13cdfm8th92ewkqc5qlsg732jcwdqwx2q7s2fnp35dr9xulr2qgxqxm969h
creation_rules:
  - path_regex: secrets.ya?ml$
    key_groups:
      - pgp:
          - *nicolas
        age:
          - *g-xps
